fullStrategy:
    source:
      url: jdbc:mysql://127.0.0.1:3306/ds_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
      username : root
      password : ilxw
    target:
      url: jdbc:mysql://127.0.0.1:3306/ds_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
      username: root
      password: root
    tableConfig:
      tables: t_ent_order,t_ent_order_detail,t_ent_order_item # 全量同步表
      switchOpen: true                                        # 是否打开开关

